---
credentials:
  rmq_port:   5672
  mgmt_port: 15672
  hosts:    (( grab jobs.node.ips ))
  username: (( grab meta.username ))
  password: (( grab meta.password ))
  uris:     (( cartesian-product "amqp://" meta.username ":" meta.password "@" jobs.node.ips ":" credentials.rmq_port ))
  uri:      (( grab credentials.uris[0] ))
