---
credentials:
  dashboard_url: ((  concat "http://" credentials.hostnames[0] ":" credentials.mgmt_port "/#/login/"  meta.username "/" meta.password ))
  rmq_port:      5672
  tls_port:      5671
  mgmt_port:     15672
  tls_mgmt_port: 15671
  hosts:         (( grab jobs.node.ips ))
  vhost:         (( grab meta.vhost || "/" ))
  username:      (( grab meta.username ))
  password:      (( grab meta.password ))
  uris:          (( cartesian-product "amqp://" meta.username ":" meta.password "@" jobs.node.ips ":" credentials.rmq_port ))
  uri:           (( grab credentials.uris[0] ))
  hostnames:     (( grab jobs.standalone/0.ips ))
  hostname:      (( grab jobs.standalone/0.ips[0] ))
  protocols:
    amqp:
      username:  (( grab meta.username ))
      password:  (( grab meta.password ))
      hosts:     (( grab jobs.node.ips ))
      host:      (( grab credentials.hosts[0] ))
      vhost:     (( grab meta.vhost || "/" ))
      port: 5672
      ssl: false
      uris:      (( grab credentials.uris ))
      uri:       (( grab credentials.protocols.amqp.uris[0] ))
    amqps:
      username:  (( grab meta.username ))
      password:  (( grab meta.password ))
      host:      (( grab jobs.node.ips[0] ))
      port: 5671
      vhost:     (( grab meta.vhost || "/" ))
      uris:      (( cartesian-product "amqps://" meta.username ":" meta.password "@" jobs.node.ips ":" credentials.tls_port ))
      uri:       (( grab credentials.protocols.amqps.uris[0] ))
      ssl: true
    management:
      username:  (( grab meta.username ))
      password:  (( grab meta.password ))
      hosts:     (( grab jobs.node.ips ))
      host:      (( grab credentials.hosts[0] ))
      path: "/api"
      port: 15672
      ssl: false
      uris:      (( cartesian-product "http://" meta.username ":" meta.password "@" jobs.node.ips ":" credentials.mgmt_port "/api" ))
      uri:       (( grab credentials.protocols.management.uris[0] ))
    management_tls:
      username:  (( grab meta.username ))
      password:  (( grab meta.password ))
      hosts:     (( grab jobs.node.ips ))
      host:      (( grab credentials.hosts[0] ))
      path: "/api"
      port: 15671
      ssl: true
      uris:      (( cartesian-product "https://" meta.username ":" meta.password "@" jobs.node.ips ":" credentials.tls_mgmt_port "/api" ))
      uri:       (( grab credentials.protocols.management_tls.uris[0] ))
