name: rabbitmq-forge-ci

instance_groups:
- name: rabbitmq-forge
  instances: 1
  azs:       [z1]
  vm_type:   default
  stemcell:  default
  networks:
    - name: default
  jobs:
    - name: rabbitmq-blacksmith-plans
      release: rabbitmq-forge
      properties:
        environment: default
        rabbitmq_metrics_emitter:
          cloud_foundry:
            username: default
            password: default
        cf:
          exodus_path: default
          deployment_name: default
          system_domain: default
          api_url: default
          username: default
          password: default
        loggregator:
          tls:
            ca_cert: default
            agent:
              cert: default
              key: default
        plans:
          standalone:
            name: standalone
            description: A single example server, with no redundancy or replication
            limit: 7
            type: standalone
            vm_type: default
          cluster:
            name: cluster
            description: An example cluster
            limit: 7
            type: cluster
            vm_type: default

update:
  canaries: 0
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000

stemcells:
- alias: default
  os: ubuntu-bionic
  version: latest

releases:
- name: rabbitmq-forge
  version: latest
